sensors:
  - id: "sensor_1"
    pin: 0
    description: ""
    dry_value: 520
    wet_value: 260
  - id: "sensor_2"
    pin: 0
    description: ""
    dry_value: 520
    wet_value: 260
  - id: "sensor_3"
    pin: 0
    description: ""
    dry_value: 520
    wet_value: 260
  - id: "sensor_4"
    pin: 0
    description: ""
    dry_value: 520
    wet_value: 260
  - id: "sensor_5"
    pin: 0
    description: ""
    dry_value: 520
    wet_value: 260
  - id: "sensor_6"
    pin: 0
    description: ""
    dry_value: 520
    wet_value: 260
  - id: "sensor_7"
    pin: 0
    description: ""
    dry_value: 520
    wet_value: 260
  - id: "sensor_8"
    pin: 0
    description: ""
    dry_value: 520
    wet_value: 260
